name: Build

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - README.md
      - icons/*
      - LICENSE

jobs:
  job_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Init gradle project
        run: ./gradlew clean

      - name: Package
        run: ./gradlew packageDeb


  job_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Init gradle project
        run: ./gradlew clean

      - name: Package
        run: ./gradlew packageMsi

  job_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Init gradle project
        run: ./gradlew clean

      - name: Package
        run: ./gradlew packageDmg